services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  api:
    build:
      context: ./django-site  
      dockerfile: Dockerfile.api
    volumes:
      - ./django-site:/code  
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork
    environment:
      - DEBUG=True
      - DJANGO_DB_NAME=db
      - DJANGO_DB_USER=admin
      - DJANGO_DB_PASSWORD=admin
      - DJANGO_DB_HOST=db

#  front:
#    build:
#      context: ./django-site  
#      dockerfile: Dockerfile.front
#    volumes:
#      - ./django-site:/usr/share/nginx/html
#    ports:
#      - "3000:3000"
#    networks:
#      - mynetwork

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - api
      - front
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork: