FROM python:latest

WORKDIR /app

COPY ./marche_stp/ /app/
COPY ./requirements.txt /app/

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && pip install --upgrade pip

RUN pip install -r requirements.txt

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]